# This is a basic workflow to help you get started with Actions

name: NJUcheckin

on: push
#   schedule:
#     - cron: '35 00 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Prepare environment
        run: pip install beautifulsoup4 lxml requests re urllib PyExecJs http
      - name: Run app
        run: python njucheckin.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
